sudo: false
language: node_js
node_js:
- stable
# - "9"
script:
- cd react-ui
- npm i
- npm test
# - rm -rf ./node_modules
- cd ../
deploy:
  provider: heroku
  app: curve-visual
  api_key:
    secure: r6qhQS7FEbLpFF9gHyra1Enq0oMSUDQl23nxykftTVmiPh9aEpExC4dClF9TqZ18s4JRnjDPp/4Cyt3E5R5g2OTfcpXhGjzeF2B1zGlyVNO//9B8EbqnCY7rQKak9Y2OT5FVoApoQRPEb88oXq+Gmxr8ihpGtSrGPz3gqha2PUWPmccvV2wunnv29fxHMjFntPyFZo19H2fNcGNXeK1wX3bXly6vwWhlr1tiCKNecrnMTN6EwJpp+tUlMCHBkdgZh4Oom55S4i2iS9IVfSM062HI9SW+gICzYgTXBIrgi281N7eXVmTwdy1Wzc938Q6IOGVoh45irrN6i+pn2JN6f9kthBdORhdCXPZc0Y3hpboiIsgw8opd+yk+qdSysPiEDwSpFcXjA1mlkqfjxDXePDEEoaI4MmjY6+fJLIC9JCJNFj0JXN4znBxc34OL08SweDQW1SbIakJgjqIcDK2kLFt1tJ1TYUefvwf5PK3AIddVZ9XHDEDLLu53NNMj31vPZbkMKVkTAxVcfx+fzQVe2F8JyAi6QjSfEnGikbGLW458wuqxBtUFcNvQih8VvqIfuO64HwXfB2uRY0xrt5VuphRG8YMK+sw69Y3/ePS4OQN2yvGPPKH7NCZF6vSXZ8Eug+7siLA5tov50SqmujuWgLQd74VPptXUOxY0onanv2w=
