sudo: false
language: node_js
node_js:
  - "10"
script:
  - cd react-ui
  - npm i
  - npm test
  - rm -rf ./node_modules
  - cd ../
  - npm i
  - npm test
  - rm -rf ./node_modules
deploy:
  provider: heroku
  app: curve-visual
  api_key:
    secure: jSZFACU0YRM/dfUiLLDgC04K+Z06IxSm/+1chKIyC24C2lckinvX7WhWxPJmR364w1kP3Dr4jroqx0SFUs0bYaFILC5Uq5tziGzOWWjDjg3zyQQD54E1TkjFC2zPa6evW/WZyrr2NgQIuZJN8h8OO9NISf5lhTtw4UGGyNRiFsCrXpxBrceCOLPVY7ID9NmMzSmya2aIKD6RNMU8LXyXcgZRshbXUehPh3yi/cmVjyZ71sfNR1+n34TIDIFStjoMIhUliRrDBn0n0dURbJicbPYaGEpmEGVb+RaJQw6Tmg1E5OyLXZLH5xUQ9fEEyu1HmQv+jYeKbnmZBBWHG6y4GWdyM7iAW1IFTW6OQtHR4wNQF6Vm/p9Th/EGyeCsop4ylABOZlpPX1ojtIgF3JRngniN7/FbagCZtCOqMYApn4Z707l1stkbUv9Dyn7MyWQ/ZagYZa5FJaCKz6/E09cKX9s9KJV86shYdGZKBlchAfhliwcBhSk/JK4vFat7Cn0PMGPbT6eI6vEilbPWUXT9/6yxH2sADDIFIMN5UOZR0+ZWhGRDkMwEb8rKQMrdRJ9VWPL/BlZLUOKRazzqmPqryhvklRX5w6BXoNX63gDGd0O0cSNxX97TJooeFOMXejFhZnmewZ/SjvcPYxF0fWlxnj2eAnmv9icGPsgm7vQmcWQ=
