version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env.production
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
    ports:
      - "54320:5432"
    env_file: .env.production
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
